### ISSUE TITLE
无法生成报告

### ISSUE THREAD

**Issue by Shadowlove9** [NorthCityChen/AutoRge#1]
emm突然发现的问题 修改zjie.json后无法生成报告 并会显示
![3Q (_TA2W0J{VR6P}SKNJP(1)](https://user-images.githubusercontent.com/65265316/82337001-c9748b80-99da-11ea-9231-71f689bb45fd.png)

顺便，这是我进行更改后的zjie
![F}2%Q98}BSQD6B(WM~XU4{H](https://user-images.githubusercontent.com/65265316/82335602-19525300-99d9-11ea-879f-4bc2f4005cf4.png)

(这个问题同时存在于简单版和完整版)

**Comment by NorthCityChen** [comment]
这个是由于windows在处理文本的时候默认使用了bom导致的，已在程序中修复

**Comment by Shadowlove9** [comment]
> 这个是由于windows在处理文本的时候默认使用了bom导致的，已在程序中修复

nice非常顶 thank you
